[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@diamond/=src/',
    '@diamond-script/=script/',
    '@diamond-test/=test/',
    '@diamond-storage/=src/libraries/storage/',
    '@diamond-logs/=src/libraries/logs/',
    '@diamond-errors/=src/libraries/errors/'
]
optimizer_runs = 20_000
